### ISSUE TITLE
Having examples with less restrictive license than LGPL

### ISSUE THREAD

**Issue by mankeli** [libopencm3/libopencm3-examples#165]
Would it make any sense to license examples as something less restrictive than LGPL? (such as BSD or even public domain)

Libopencm3 is really nice to use,and it might enjoy more widespread adaptation if users would be able to do base their creations on the examples without have to worry about LGPL's restrictions.

**Comment by karlp** [comment]
well, you have to worry about LGPL for the _library_ so I don't see what the problem is.  (I mean, I kinda do, but good luck finding all the authors to try and change it)

There are other examples out there, and it's entirely up to  you and your lawyer when you feel you have "copied" an example, vs "used the example as reference code"
